/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as ActivationRouteImport } from './routes/activation'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppUsersRouteImport } from './routes/app.users'
import { Route as AppTemplatesRouteImport } from './routes/app.templates'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppRbiRouteImport } from './routes/app.rbi'
import { Route as AppPublishRouteImport } from './routes/app.publish'
import { Route as AppNdtImportRouteImport } from './routes/app.ndt-import'
import { Route as AppMediaRouteImport } from './routes/app.media'
import { Route as AppInspectionsRouteImport } from './routes/app.inspections'
import { Route as AppEquipmentRouteImport } from './routes/app.equipment'
import { Route as AppDraftsRouteImport } from './routes/app.drafts'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppCertificatesRouteImport } from './routes/app.certificates'
import { Route as AppBrandingRouteImport } from './routes/app.branding'
import { Route as AppAuditRouteImport } from './routes/app.audit'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivationRoute = ActivationRouteImport.update({
  id: '/activation',
  path: '/activation',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppTemplatesRoute = AppTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppRbiRoute = AppRbiRouteImport.update({
  id: '/rbi',
  path: '/rbi',
  getParentRoute: () => AppRoute,
} as any)
const AppPublishRoute = AppPublishRouteImport.update({
  id: '/publish',
  path: '/publish',
  getParentRoute: () => AppRoute,
} as any)
const AppNdtImportRoute = AppNdtImportRouteImport.update({
  id: '/ndt-import',
  path: '/ndt-import',
  getParentRoute: () => AppRoute,
} as any)
const AppMediaRoute = AppMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AppRoute,
} as any)
const AppInspectionsRoute = AppInspectionsRouteImport.update({
  id: '/inspections',
  path: '/inspections',
  getParentRoute: () => AppRoute,
} as any)
const AppEquipmentRoute = AppEquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => AppRoute,
} as any)
const AppDraftsRoute = AppDraftsRouteImport.update({
  id: '/drafts',
  path: '/drafts',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCertificatesRoute = AppCertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => AppRoute,
} as any)
const AppBrandingRoute = AppBrandingRouteImport.update({
  id: '/branding',
  path: '/branding',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activation': typeof ActivationRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/audit': typeof AppAuditRoute
  '/app/branding': typeof AppBrandingRoute
  '/app/certificates': typeof AppCertificatesRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/drafts': typeof AppDraftsRoute
  '/app/equipment': typeof AppEquipmentRoute
  '/app/inspections': typeof AppInspectionsRoute
  '/app/media': typeof AppMediaRoute
  '/app/ndt-import': typeof AppNdtImportRoute
  '/app/publish': typeof AppPublishRoute
  '/app/rbi': typeof AppRbiRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/templates': typeof AppTemplatesRoute
  '/app/users': typeof AppUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activation': typeof ActivationRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/audit': typeof AppAuditRoute
  '/app/branding': typeof AppBrandingRoute
  '/app/certificates': typeof AppCertificatesRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/drafts': typeof AppDraftsRoute
  '/app/equipment': typeof AppEquipmentRoute
  '/app/inspections': typeof AppInspectionsRoute
  '/app/media': typeof AppMediaRoute
  '/app/ndt-import': typeof AppNdtImportRoute
  '/app/publish': typeof AppPublishRoute
  '/app/rbi': typeof AppRbiRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/templates': typeof AppTemplatesRoute
  '/app/users': typeof AppUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activation': typeof ActivationRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/audit': typeof AppAuditRoute
  '/app/branding': typeof AppBrandingRoute
  '/app/certificates': typeof AppCertificatesRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/drafts': typeof AppDraftsRoute
  '/app/equipment': typeof AppEquipmentRoute
  '/app/inspections': typeof AppInspectionsRoute
  '/app/media': typeof AppMediaRoute
  '/app/ndt-import': typeof AppNdtImportRoute
  '/app/publish': typeof AppPublishRoute
  '/app/rbi': typeof AppRbiRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/templates': typeof AppTemplatesRoute
  '/app/users': typeof AppUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activation'
    | '/app'
    | '/auth'
    | '/app/audit'
    | '/app/branding'
    | '/app/certificates'
    | '/app/dashboard'
    | '/app/drafts'
    | '/app/equipment'
    | '/app/inspections'
    | '/app/media'
    | '/app/ndt-import'
    | '/app/publish'
    | '/app/rbi'
    | '/app/reports'
    | '/app/settings'
    | '/app/templates'
    | '/app/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activation'
    | '/app'
    | '/auth'
    | '/app/audit'
    | '/app/branding'
    | '/app/certificates'
    | '/app/dashboard'
    | '/app/drafts'
    | '/app/equipment'
    | '/app/inspections'
    | '/app/media'
    | '/app/ndt-import'
    | '/app/publish'
    | '/app/rbi'
    | '/app/reports'
    | '/app/settings'
    | '/app/templates'
    | '/app/users'
  id:
    | '__root__'
    | '/'
    | '/activation'
    | '/app'
    | '/auth'
    | '/app/audit'
    | '/app/branding'
    | '/app/certificates'
    | '/app/dashboard'
    | '/app/drafts'
    | '/app/equipment'
    | '/app/inspections'
    | '/app/media'
    | '/app/ndt-import'
    | '/app/publish'
    | '/app/rbi'
    | '/app/reports'
    | '/app/settings'
    | '/app/templates'
    | '/app/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivationRoute: typeof ActivationRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activation': {
      id: '/activation'
      path: '/activation'
      fullPath: '/activation'
      preLoaderRoute: typeof ActivationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/users': {
      id: '/app/users'
      path: '/users'
      fullPath: '/app/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/templates': {
      id: '/app/templates'
      path: '/templates'
      fullPath: '/app/templates'
      preLoaderRoute: typeof AppTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/rbi': {
      id: '/app/rbi'
      path: '/rbi'
      fullPath: '/app/rbi'
      preLoaderRoute: typeof AppRbiRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/publish': {
      id: '/app/publish'
      path: '/publish'
      fullPath: '/app/publish'
      preLoaderRoute: typeof AppPublishRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ndt-import': {
      id: '/app/ndt-import'
      path: '/ndt-import'
      fullPath: '/app/ndt-import'
      preLoaderRoute: typeof AppNdtImportRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/media': {
      id: '/app/media'
      path: '/media'
      fullPath: '/app/media'
      preLoaderRoute: typeof AppMediaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inspections': {
      id: '/app/inspections'
      path: '/inspections'
      fullPath: '/app/inspections'
      preLoaderRoute: typeof AppInspectionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/equipment': {
      id: '/app/equipment'
      path: '/equipment'
      fullPath: '/app/equipment'
      preLoaderRoute: typeof AppEquipmentRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/drafts': {
      id: '/app/drafts'
      path: '/drafts'
      fullPath: '/app/drafts'
      preLoaderRoute: typeof AppDraftsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/certificates': {
      id: '/app/certificates'
      path: '/certificates'
      fullPath: '/app/certificates'
      preLoaderRoute: typeof AppCertificatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/branding': {
      id: '/app/branding'
      path: '/branding'
      fullPath: '/app/branding'
      preLoaderRoute: typeof AppBrandingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/audit': {
      id: '/app/audit'
      path: '/audit'
      fullPath: '/app/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAuditRoute: typeof AppAuditRoute
  AppBrandingRoute: typeof AppBrandingRoute
  AppCertificatesRoute: typeof AppCertificatesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDraftsRoute: typeof AppDraftsRoute
  AppEquipmentRoute: typeof AppEquipmentRoute
  AppInspectionsRoute: typeof AppInspectionsRoute
  AppMediaRoute: typeof AppMediaRoute
  AppNdtImportRoute: typeof AppNdtImportRoute
  AppPublishRoute: typeof AppPublishRoute
  AppRbiRoute: typeof AppRbiRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTemplatesRoute: typeof AppTemplatesRoute
  AppUsersRoute: typeof AppUsersRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAuditRoute: AppAuditRoute,
  AppBrandingRoute: AppBrandingRoute,
  AppCertificatesRoute: AppCertificatesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDraftsRoute: AppDraftsRoute,
  AppEquipmentRoute: AppEquipmentRoute,
  AppInspectionsRoute: AppInspectionsRoute,
  AppMediaRoute: AppMediaRoute,
  AppNdtImportRoute: AppNdtImportRoute,
  AppPublishRoute: AppPublishRoute,
  AppRbiRoute: AppRbiRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTemplatesRoute: AppTemplatesRoute,
  AppUsersRoute: AppUsersRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivationRoute: ActivationRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
